### ISSUE TITLE
When i try to create new activity i got this 

### ISSUE THREAD

**Issue by ergib** [jiwomdf/solat-kuy-android-mvvm-with-coroutine#7]
Selam
C:\Users\User\Downloads\Solat Kuy\PrayerTime 21_7_22\app\build\tmp\kapt3\stubs\debug\com\programmergabut\solatkuy\data\local\localentity\MsNotifiedPrayer.java:16: error: Room cannot pick a constructor since multiple constructors are suitable. Try to annotate unwanted constructors with @Ignore.
    public MsNotifiedPrayer(@org.jetbrains.annotations.NotNull()
           ^
![image](https://user-images.githubusercontent.com/69704611/182029619-198a73a5-a578-4bb7-a7db-f70e27cb35e9.png)

Please could you help me, im stuck in this error for days,(begginer in mvvm)

**Comment by jiwomdf** [comment]
hi Salam
Okee, will try and hit you when I found the solution
thanks for the report

**Comment by ergib** [comment]
thanks a lot that would be so helpful to me , like beginner in mvvm

**Comment by jiwomdf** [comment]
hi bro, can I know what do you want to achieve? 
do you want to run the project after cloning but got an error?
can you tell me the previous step that you have done?

thanks broo

**Comment by ergib** [comment]
Hey brother, thanks for response, when i try to add new activity in your
project , i got error in photo, i wanna ask you can connect 2-3 min with
teamviewer or any desk,without wasting your time, thanks:)

**Comment by jiwomdf** [comment]
I think not team viewer bro, I dont have it
maybe google call?

**Comment by ergib** [comment]
sure brother, send me the link please

**Comment by jiwomdf** [comment]
https://meet.google.com/dzx-cdws-gyj here, will delete the link after one day bro @ergib

**Comment by jiwomdf** [comment]
after discussing with @ergib it happen because of the "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version" is changing to "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21". Still not sure why it's changing 

thanks @ergib for the report
